const ConfigConst = {
    KEY: "cn40'9@W+9)S&7§:e9+.{&y&uÙtA!h[3R-31:l'5]]:h$0>@ui!0z$FIiU£lb9H6BFST+*§[TwSdjm7.6)26N§=>)068geSUeY£!R%[£0!£%+8.IQ&(N/&Ipi%)Lm;.B3}D/1hvnSNlZJA]G[,2}v(9[<}-73z=/pJ$kQ0UQhp<n<]--x!=S.O;.§§*tBPwE§£CmgiXK",
    DISCORD: "https://discord.gg/5mF5AHnRCr",
    GITHUB: "https://github.com/ShadowoftheRedFox/Kyrazail-Adventure-Dev.git",
    LANGUAGE: "en",
    ZINDEX: {
        UNKNOWN: 0,
        MAP: 1,
        MAPANIMATED: 2,
        ENTITIES: 3,
        MAPOVER: 4,
        MAPEFFECT: 5,
        FIGHT: 6,
        PLAYERQUIPEMENT: 7,
        DIALOGUE: 8,
        PAUSE: 9,
        MAIN: 900,
        MAINSUBMENU: 901,
        INTRODUCTION: 950,
        TRANSITION: 998,
        LOADING: 999,
        ERROR: 1000
    },
    TIP: [
        "Why is mana blue?",
        "Don't forget to save often!",
        "Bosses can give you special items!",
        "Use potions if the fight is too tough.",
        "Stronger monsters give you better loots!",
        "Found a bug? Check out our Discord to report it!",
        "Monsters respawn after a certain amount of time...",
        "The most expensive equipement is not always the best...",
        "You can try to escape any fight, but you better be lucky.",
        "Search around the map, maybe you will find something interesting...",
        "There is a land were God left something... It's a myth of course, right?",
        "You can find Dinarks everywhere. You can even make them if you know how!",
    ],
    TITLE: [
        "e^(iπ)+1=0",
        "Touch grass.",
        "erutnevdA liazaryK",
        "The forbidden name...",
        "Don't drink pure mana!",
        "Maybe gold is useless...",
        "Violence is not a solution, it's THE solution.",
    ],
    CONTAINER: (function () { return document.getElementById("container"); })(),
    MAINCONTAINER: (function () { return document.body; })(),
    DEBUG: false
};
//TODO add constants for animation speed, click, frame time etc